#!/bin/bash

function urgencies0 {
var0=$(dialog --title ' ' --backtitle "Restauracao de Containers" --ok-label "Acessar" --cancel-label "Voltar" --menu " " 0 0 0 \
1 'Restaurar Containers Localmente' \
2 'Download Backups de Containers' \
3 'Refazer Todo o Servidor!' \
4 'Forçar um Backup Pontual' \
X '<' 2>&1 > /dev/tty )
case "$var0" in
1) clear ; curl -sSL https://raw.githubusercontent.com/urbancompasspony/server/refs/heads/main/CDN/01-Restore_BKP | bash ; urgencies0 ;;
2) clear ; curl -sSL https://raw.githubusercontent.com/urbancompasspony/server/refs/heads/main/CDN/02-Restore_Cloud | bash ; urgencies0 ;;
3) clear ; restoreconfirm0 ; urgencies0 ;;
4) clear ; sudo bash /srv/scripts/bkp-cdn.sh ; urgencies0 ;;
X) echo "." >/dev/null ;;
esac
}

function restoreconfirm0 {
  VALUE0=$(dialog --ok-label "Restaurar" --title "Restauracao Total" --form "Restaurando o servidor: \n\n$file\n\nPOR FAVOR CONFIRME QUE VOCE ESTA DE ACORDO COM OS RISCOS INERENTES A ESTA RESTAURACAO! \n\nRepita no campo abaixo: \neu estou ciente dos riscos" 18 50 0 \
"." 1 1 "$VALUE1" 1 1 50 0 \
3>&1 1>&2 2>&3 3>&- > /dev/tty)
    case $? in
      0) echo "." > /dev/null ;;
      1) exit 0 ;;
    esac
    var1=$(echo "$VALUE0" | sed -n 1p)
    [ "$var1" = "eu estou ciente dos riscos" ] && {
      clear
      echo "5"
      echo "O SERVIDOR SERÁ COMPLETAMENTE RESTAURADO BASEADO NO BACKUP ENCONTRADO!"
      sleep 1
      echo "4"
      echo "NÃO TENTE INTERAGIR COM O SISTEMA DURANTE A RESTAURAÇÃO COMPLETA."
      sleep 1
      echo "3"
      echo "SE POSSÍVEL DESCONECTE TECLADO E MOUSE, NÃO INTERAJA COM ABSOLUTAMENTE NADA ATÉ CONCLUIR!"
      sleep 1
      echo "2"
      echo "SE QUISER DESISTIR AGORA PRESSIONE   CTRL + C"
      sleep 1
      echo "1"
      echo "NÃO DESLIGUE O SERVIDOR ATÉ O MOMENTO DO REINÍCIO AUTOMÁTICO."
      sleep 1
      echo "Restauração Iniciada..."
      echo "Tenha uma boa sorte!"
      sleep 2
      clear
      curl -sSL https://raw.githubusercontent.com/urbancompasspony/server/refs/heads/main/CDN/ReDo/2-Restore_Total.sh | sudo bash
    } || {
      clear; echo ""; echo "Repete a frase exatamente como estou pedindo, por favor! Saindo..."
      sleep 3
    }
}

urgencies0

exit 0
