#!/bin/bash

function urgencies0 {
var0=$(dialog --title ' ' --backtitle "Restauracao de Containers" --ok-label "Acessar" --cancel-label "Voltar" --menu " " 0 0 0 \
1 'Restaurar Containers Localmente' \
2 'Download Backups de Containers' \
3 'Refazer Todo o Servidor' \
X '<' 2>&1 > /dev/tty )
case "$var0" in
1) clear ; curl -sSL https://raw.githubusercontent.com/urbancompasspony/server/refs/heads/main/CDN/01-Restore_BKP | bash ; urgencies0 ;;
2) clear ; curl -sSL https://raw.githubusercontent.com/urbancompasspony/server/refs/heads/main/CDN/02-Restore_Cloud | bash ; urgencies0 ;;
3) clear ; echo "EM BREVE!" ; urgencies0 ;;
X) echo "." >/dev/null ;;
esac
}

urgencies0

exit 1
