#!/bin/bash

# CREATE NETWORK DEVICES AS BRIDGE, NEVER AS VEPA, 'CUZ THIS CONFLICTS WITH MACVLAN DOCKER!

##############
# Parameters #
##############

destpath="/var/lib/libvirt/images"

sudo mkdir -p "$destpath"
sudo chmod 777 -R "$destpath"

serverip="172.20.0.22"
lanhost="http://$serverip"
wanhost="http://z.net-freaks.com:3434"

usern4me="admin"
passw0rd="isorulez"

# Check where get the .img file
if ping -c 1 $serverip >/dev/null; then
    webadress="$lanhost"
else
    webadress="$wanhost"
fi

#############
# Functions #
#############

function check {
  [ "$EUID" -ne 0 ] && {
    echo "Execute esse script como Root!"
    exit
    }
}

function start {
  [ -f /var/lib/libvirt/images/pfsense.img ] && {
    setinter
    echo "." >/dev/null
  } || {
    calling pfsense.img
    setperma
    setinter
  }
}

function calling {
  clear
  sudo wget --user $usern4me --password $passw0rd $webadress/$1 -O $destpath/$1
}

function setperma {
  sudo chmod 777 -R "$destpath"
}

function setinter {
  # Get my main LAN (usually motherboard)
  mylan=$(ip route get 1.1.1.1 2>/dev/null | grep -oP 'dev \K\S+')

  # Create an Array but eliminating docker, veth, lo, tun, virbr, macv and myself (mylan) from that!
  myarray=($(ls /sys/class/net/ | grep -v "docker" | grep -v "veth" | grep -v "lo" | grep -v "virbr" | grep -v "macv" | grep -v "tun" | grep -v "$mylan"))
  
  # With the remaining connection interfaces, create the aspects of menu. (Do not try to set order based on appliance pfsense!
  VALUE1="${myarray[0]}"; VALUE2="${myarray[1]}"; VALUE3="${myarray[2]}"; VALUE4="${myarray[3]}"

  # If array is empty, fill with zero!
  [ "${myarray[0]}" = "" ] && { VALUE1="0"; } || { echo "." >/dev/null ; }
  [ "${myarray[1]}" = "" ] && { VALUE2="0"; } || { echo "." >/dev/null ; }
  [ "${myarray[2]}" = "" ] && { VALUE3="0"; } || { echo "." >/dev/null ; }
  [ "${myarray[3]}" = "" ] && { VALUE4="0"; } || { echo "." >/dev/null ; }

  VALUE0=$(dialog --help-button --help-label "Dica" --ok-label "Criar" --title "Definir Interfaces" --form "O que estiver zero nao sera utilizado!" 13 40 0 \
"IP LAN 0:" 1 1 "$VALUE1" 1 11 30 0 \
"IP LAN 1:" 2 1 "$VALUE2" 2 11 30 0 \
"IP LAN 2:" 3 1 "$VALUE3" 3 11 30 0 \
"IP LAN 3:" 4 1 "$VALUE4" 4 11 30 0 \
3>&1 1>&2 2>&3 3>&- > /dev/tty)

  case $? in
    0) echo "." > /dev/null ;;
    1) return ;;
    2) dialognet ; setinter ;;
  esac

  var1=$(echo "$VALUE0" | sed -n 1p)
  var2=$(echo "$VALUE0" | sed -n 2p)
  var3=$(echo "$VALUE0" | sed -n 3p)
  var4=$(echo "$VALUE0" | sed -n 4p)

  [ $var3 = "0" ] && [ $var4 = "0" ] && { createvm2 "$var1" "$var2"; }

  [ $var4 = "0" ] && { createvm3 "$var1" "$var2" "$var3"; }

  createvm4 "$var1" "$var2" "$var3" "$var4"
}

function dialognet {
  dialog --title "Informação" --msgbox "Checar a existencia de altnames nas informacoes a seguir!" 7 40
  dialog --title "Informação" --msgbox "$(ip a)" 25 70
}

function createvm2 {
  virt-install --import \
--name pfSense \
--boot hd,cdrom,menu=on \
--memory 2048 \
--vcpus 2 \
--cpu host \
--network type=direct,source=$1,source_mode=bridge,mac=52:54:00:55:ea:01 \
--network type=direct,source=$2,source_mode=bridge,mac=52:54:00:55:ea:02 \
--disk /var/lib/libvirt/images/pfsense.img \
--os-variant=freebsd13.1 \
--graphics vnc \
--import \
--autostart 1>/dev/null 2>/dev/null &

dialog --title "Informação" --msgbox "Se a maquina virtual nao existia, ela sera criada e inicializada!" 6 40
dialog --title "Informação" --msgbox "Verifique o status da maquina virtual pelo Virt-Manager, digitando o comando startx!" 6 60

exit
}

function createvm3 {
  virt-install --import \
--name pfSense \
--boot hd,cdrom,menu=on \
--memory 2048 \
--vcpus 2 \
--cpu host \
--network type=direct,source=$1,source_mode=bridge,mac=52:54:00:55:ea:01 \
--network type=direct,source=$2,source_mode=bridge,mac=52:54:00:55:ea:02 \
--network type=direct,source=$3,source_mode=bridge,mac=52:54:00:55:ea:03 \
--disk /var/lib/libvirt/images/pfsense.img \
--os-variant=freebsd13.1 \
--graphics vnc \
--import \
--autostart 1>/dev/null 2>/dev/null &

dialog --title "Informação" --msgbox "Se a maquina virtual nao existia, ela sera criada e inicializada!" 6 40
dialog --title "Informação" --msgbox "Verifique o status da maquina virtual pelo Virt-Manager, digitando o comando startx!" 6 60

exit
}

function createvm4 {
  virt-install --import \
--name pfSense \
--boot hd,cdrom,menu=on \
--memory 2048 \
--vcpus 2 \
--cpu host \
--network type=direct,source=$1,source_mode=bridge,mac=52:54:00:55:ea:01 \
--network type=direct,source=$2,source_mode=bridge,mac=52:54:00:55:ea:02 \
--network type=direct,source=$3,source_mode=bridge,mac=52:54:00:55:ea:03 \
--network type=direct,source=$4,source_mode=bridge,mac=52:54:00:55:ea:04 \
--disk /var/lib/libvirt/images/pfsense.img \
--os-variant=freebsd13.1 \
--graphics vnc \
--import \
--autostart 1>/dev/null 2>/dev/null &

dialog --title "Informação" --msgbox "Se a maquina virtual nao existia, ela sera criada e inicializada!" 6 40
dialog --title "Informação" --msgbox "Verifique o status da maquina virtual pelo Virt-Manager, digitando o comando startx!" 6 60

exit
}

#########
# Start #
#########

check
start

exit 1
