#!/bin/bash

function check {
  [ "$EUID" -ne 0 ] && {
    echo "Execute esse script como Root!"
    exit
    }
}

destpath="/var/lib/libvirt/images"

sudo mkdir -p "$destpath"
sudo chmod 777 -R "$destpath"

serverip="172.20.0.22"
lanhost="http://$serverip"
wanhost="http://cs.linuxuniverse.com.br:3434"

usern4me="admin"
passw0rd="isorulez"

if ping -c 1 $serverip >/dev/null; then
    webadress="$lanhost"
else
    webadress="$wanhost"
fi

function createvm {
virt-install --import \
--name pfSense \
--boot hd,cdrom,menu=on \
--memory 2048 \
--vcpus 2 \
--cpu host \
--network type=direct,source=enp1s0,source_mode=vepa,mac=52:54:00:55:ea:01 \
--network type=direct,source=enp2s0,source_mode=vepa,mac=52:54:00:55:ea:02 \
--disk /var/lib/libvirt/images/pfsense.img \
--os-variant=freebsd13.1 \
--graphics vnc \
--import \
--autostart 1>/dev/null 2>/dev/null &

dialog --title "Informação" --msgbox "A máquina virtual está sendo criada e inicializada!" 6 40
dialog --title "Informação" --msgbox "Verifique o status da máquina virtual pelo Virt-Manager, digitando o comando startx!" 6 60

exit
}

function calling {
  clear
  sudo wget --user $usern4me --password $passw0rd $webadress/$1 -O $destpath/$1
}

function setperma {
  sudo chmod 777 -R "$destpath"
}

check

[ -f /var/lib/libvirt/images/pfsense.img ] &&
  createvm
} || {
  calling pfsense.img
  setperma
  createvm
}

exit 1
