#!/bin/bash

sudo apt install glusterfs-client glusterfs-server

ssh-keygen -t rsa -b 4096

ssh-copy-id administrador@cluster-01
ssh-copy-id administrador@cluster-02

sudo apt install -y \
    software-properties-common \
    apt-transport-https \
    ca-certificates \
    curl \
    dpkg \
    gcc \
    sed \
    sudo \
    grep \
    wget \
    xterm \
    less \
    gpgv \
    libfuse2 \
    libglib2.0-0 \
    libxext6 \
    libsm6 \
    libxrender1 \
    lsb-release \
    mesa-utils \
    xvfb \
    ssh-askpass \
    virt-manager \
    dbus-x11 \
    libglib2.0-bin \
    gir1.2-spiceclientgtk-3.0

sudo apt-get install -y wget && \
    wget -q https://xpra.org/gpg.asc -O- | sudo apt-key add - &&  \
    echo "deb https://xpra.org/ jammy main" | sudo tee -a /etc/apt/sources.list.d/xpra.list && \
    sudo apt-get update && \
    sudo apt-get install -y xpra
