#!/bin/bash

export NEEDRESTART_MODE=a
export DEBIAN_FRONTEND=noninteractive

export bktitle="Headscale Manager Menu"
export ttitle=" v1.0 "

function main_menu {
  var4=$(dialog --title "$ttitle" --backtitle "$bktitle" --menu " " 0 0 0 \
  A 'Gerenciar Maquinas' \
  B 'Gerenciar Usuarios' \
  C 'Gerenciar Rotas' \
  D 'Gerenciar API Keys' \
  D 'Gerar Chave Privada' \
  X 'Sair' 2>&1 > /dev/tty )
  [ $? -ne 0 ] && exit
  case "$var4" in
  A) nodelist ; main_menu ;;
  B) userlist ; main_menu ;;
  C) ; main_menu ;;
  D) ; main_menu ;;
  D) headscale generate private-key ; main_menu ;;
  X) exit ;;
  esac
}

function nodelist {
  headscale nodes list
}

function userlist {
  headscale users list
}

function dica0 {
  VALUE2=$(dialog --stdout --backtitle "Use as setas para navegar nos diretorios abaixo, use ESPACO 2x para confirmar uma pasta!" --title "Escolha a pasta alvo!" --dselect "/mnt" 15 40 | tail -c +5)
}

# Start all!
main_menu

# If any error...
exit 1
