#!/bin/bash

# For Ubuntu!
export pty=True
export NEEDRESTART_MODE=a
export DEBIAN_FRONTEND=noninteractive

function check {
  [ "$EUID" -ne 0 ] && {
    echo "Execute esse script como Root!"
    exit
    }
}

destpath="/var/lib/libvirt/images"

sudo mkdir -p "$destpath"
sudo chmod 777 -R "$destpath"

serverip="172.20.0.22"
lanhost="http://$serverip"
wanhost="http://cs.linuxuniverse.com.br:3434"

usern4me="admin"
passw0rd="isorulez"

if ping -c 1 $serverip >/dev/null; then
    webadress="$lanhost"
else
    webadress="$wanhost"
fi

function start {
var0=$(dialog --title ' ' --backtitle "Bem-Vindo ao ISO Downloader!" --menu " " 0 0 0 \
1 'pfSense 2.7' \
2 'Windows Server 2019 STD' \
3 'Windows 10 Pro/Works' \
4 'Windows 11 Pro/Works' \
5 'ReviOS W10' \
6 'ReviOS W11' \
7 'Drivers VM VirtIO' \
X '<' 2>&1 > /dev/tty )
case "$var0" in
1) calling pfSense-2.7.iso ; setperma ; start ;;
2) calling wserver2019STD.iso ; setperma ; start ;;
3) calling Windows10.iso ; setperma ; start ;;
4) calling Windows11.iso ; setperma ; start ;;
5) calling ReviOSW10.iso ; setperma ; start ;;
6) calling ReviOSW11.iso ; setperma ; start ;;
7) clear ; sudo wget https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/stable-virtio/virtio-win.iso -O $destpath/$1 ; setperma ; start ;;
X) echo "Saindo..." ;;
esac
}

function calling {
  clear
  sudo wget --user $usern4me --password $passw0rd $webadress/$1 -O $destpath/$1
}

function setperma {
  sudo chmod 777 -R "$destpath"
}

check
start
