#!/bin/bash

# For Ubuntu!
export pty=True
export NEEDRESTART_MODE=a
export DEBIAN_FRONTEND=noninteractive

function check {
  [ "$EUID" -ne 0 ] && {
    echo "Execute esse script como Root!"
    exit
    }
}

destpath="/var/lib/libvirt/images"

sudo mkdir -p "$destpath"
sudo chmod 777 -R "$destpath"

serverip="172.20.0.22"
lanhost="http://$serverip"
wanhost="http://cs.linuxuniverse.com.br:3434"

usern4me="admin"
passw0rd="isorulez"

if ping -c 1 $serverip >/dev/null; then
    webadress="$lanhost"
else
    webadress="$wanhost"
fi

function start {
var0=$(dialog --title ' ' --backtitle "Bem-Vindo ao ISO Downloader!" --menu " " 0 0 0 \
A 'pfSense IMG' \
B 'pfSense 2.7' \
C 'pfSense 2.6' \
D 'Ubuntu Server 22.04 LTS' \
E 'Windows Server 2019 STD' \
F 'Windows 10' \
G 'Windows 11' \
H 'ReviOS W10' \
I 'ReviOS W11' \
J 'virtio-win-0.1.185' \
K 'virtio-win-0.1.229' \
X '<' 2>&1 > /dev/tty )
case "$var0" in
A) calling pfSense.img ; setperma ; start ;;
B) calling pfSense-2.7.iso ; setperma ; start ;;
C) calling pfSense2.6.iso ; setperma ; start ;;
D) calling ubuntuserver2204.iso ; setperma ; start ;;
E) calling wserver2019STD.iso ; setperma ; start ;;
F) calling Windows10.iso ; setperma ; start ;;
G) calling Windows11.iso ; setperma ; start ;;
H) calling ReviOSW10.iso ; setperma ; start ;;
I) calling ReviOSW11.iso ; setperma ; start ;;
J) calling virtio-win-0.1.185.iso ; setperma ; start ;;
K) calling virtio-win-0.1.229.iso ; setperma ; start ;;
X) echo "Saindo..." ;;
esac
}

function calling {
  clear
  sudo wget --user $usern4me --password $passw0rd $webadress/$1 -O $destpath/$1
}

function setperma {
  sudo chmod 777 -R "$destpath"
}

check
start
