#!/bin/bash

extensoes="\\.micro$|\\.zepto$|\\.cerber$|\\.locky$|\\.cerber3$|\\.cryp1$|\\.mole$|\\.onion$|\\.axx$|\\.osiris$|\\.crypz$|\\.crypt$|\\.locked$|\\.odin$|\\.ccc$|\\.cerber2$|\\.sage$|\\.globe$|\\.exx$|\\.good$|\\.wallet$|\\.1txt$|\\.decrypt2017$|\\.encrypt$|\\.ezz$|\\.zzzzz$|\\.MERRY$|\\.enciphered$|\\.r5a$|\\.aesir$|\\.ecc$|\\.enigma$|\\.cryptowall$|\\.encrypted$|\\.loli$|\\.breaking_bad$|\\.coded$|\\.ha3$|\\.damage$"

customname="/srv/containers/SAMBA_SHARE"

function ransomfunc {
  cat "$1"/log/syslog | egrep -i "$extensoes"
}

[ -d /srv/containers/dominio ] && {
  ransomfunc "/srv/containers/dominio"
}

[ -d "$customname" ] && {
  ransomfunc "$customname"
}

exit 1
