#!/bin/bash

# # # # # # # # # # #
# SRV MGR Menu v0.1 #
# # # # # # # # # # # 

# For Ubuntu!
export pty=True
export NEEDRESTART_MODE=a
export DEBIAN_FRONTEND=noninteractive

# Hash
hash1="68b329da9893e34099c7d8ad5cb9c940"

# Versão:
version="v2.0"

# ------------------------------------------------------------------------------

# PASSWORD
function init {
password=$(dialog --backtitle "Server Manager $version" --title " " --insecure --passwordbox "Digite a senha!" 0 0 2>&1 > /dev/tty)
hash0=$(echo "$password" | md5sum | awk '{print $1}')
  [ $? -ne 0 ] && exit
  [ -z "$password" ] && {
      dialog --title "ERROR" --msgbox "É necessário digitar uma senha para continuar." 6 40
      clear
  } || {
    [ "$hash0" = "$hash1" ] && {
      start
    } || {
      clear
      dialog --title "ERROR" --msgbox "Senha incorreta. \nTente novamente!" 6 30
      timeout=$((timeout+1)); sleep $timeout
      init
      }
  }
}

hash1="fe5dfdd991450623c39efc7705e47ad5"

function start {
var0=$(dialog --title ' ' --backtitle "Bem-Vindo ao Server Manager $version!" --menu " " 0 0 0 \
A 'First Configuration' \
B 'Orchestra' \
C 'Managers' \
D 'Settings' \
E 'Reboot Server' \
F 'Shutdown Server' \
X 'Sair' 2>&1 > /dev/tty )
case "$var0" in
A) firstconfig ; start ;;
B) curl -sSL https://raw.githubusercontent.com/urbancompasspony/server/main/orchestration | bash ; start ;;
C) managers ; start ;;
D) curl -sSL https://raw.githubusercontent.com/urbancompasspony/server/main/tools | sudo bash ; start ;;
E) reb00t ;;
F) shutd0 ;;
X) exit ;;
esac
}

function firstconfig {
var0=$(dialog --title ' ' --backtitle "Fiest Configuration!" --menu " " 0 0 0 \
A 'Linite' \
B 'DWAgent [x86]' \
C 'DWAgent [ARM]' \
D 'Atualizar Bashrc' \
X 'Sair' 2>&1 > /dev/tty )
case "$var0" in
A) curl -sSL https://raw.githubusercontent.com/urbancompasspony/linite/main/linite | sudo bash ; firstconfig ;;
B) wget https://www.dwservice.net/download/dwagent_x86.sh -O /home/$USER/dwagent_x86.sh ; firstconfig ;;
C) wget https://www.dwservice.net/download/dwagent_generic.sh -O /home/$USER/dwagent_generic.sh ; firstconfig ;;
D) curl -sSL https://raw.githubusercontent.com/urbancompasspony/bashrc/main/install.sh | bash ; firstconfig ;;
X) exit ;;
esac
}

function managers {
var0=$(dialog --title ' ' --backtitle "Managers" --menu " " 0 0 0 \
A 'LazyDocker Manager' \
B 'TUI VM Manager' \
C 'Active Directory' \
D 'Samba Folder MGR' \
E 'Start Desktop' \
X '<' 2>&1 > /dev/tty )
case "$var0" in
A) lazydocker ; managers ;;
B) curl -sSL https://raw.githubusercontent.com/urbancompasspony/server/main/vm_machine | bash ; managers ;;
C) clear ; dialog --title "Informação" --msgbox "Digite domain para entrar no painel de controle do AD-DC SAMBA4!" 6 40 ; exit ;;
D) clear ; curl -sSL https://raw.githubusercontent.com/urbancompasspony/server/main/smb_folder_manager | bash ; managers ;;
E) clear ; dialog --title "Informação" --msgbox "Digite startx para entrar no modo Desktop!" 5 50 ; exit ;;
X) start ;;
esac
}

function domainlocal01 {
  [ $(which docker 2>/dev/null) ] && {
    docker ps -a | grep dominio 1> /dev/null && {
      domain
    } || {
      domainlocal02
    }
  } || {
    domainlocal02
  }
}

function domainlocal02 {
sambastatus=$(ps aux | grep "domain" | grep -v grep 1> /dev/null && echo "Executando" || echo "Parado")
  [ "$sambastatus" = "Executando" ] && {
    curl -sSL https://raw.githubusercontent.com/urbancompasspony/server/main/domain | sudo bash
  } || {
    dialog --cr-wrap --title 'Atenção!' --backtitle "$bktitle" --msgbox "Nenhum Controlador de Domínio localizado." 8 40
    }
}

hash1="e4439267203fb5277d347e6cd6e440b5"

function reb00t {
  dialog --title 'Reiniciar' --backtitle "Reinício" --yesno 'Deseja reiniciar este sistema?' 0 0
  [ $? = 0 ] && {
    sudo reboot
  } || {
    start
  }
}

hash1="576200e78f0ab25b437dc7372ae920d9"

function shutd0 {
  dialog --title 'Desligar' --backtitle "Desligamento" --yesno 'Deseja desligar este sistema?' 0 0
  [ $? = 0 ] && {
    sudo shutdown -h now
  } || {
    start
  }
}

# ------------------------------------------------------------------------------

[ "$EUID" -ne 0 ] || {
  echo "Não execute esse script com sudo! Saindo..."
  exit
  }

# Checagem Obrigatória de Dependências:
[ -f /home/$USER/.installed ] || {
  [ -f /usr/bin/pacman ] && {
    clear
    echo "Por favor, insira a senha do usuário $USER!"
    echo ""
    curl -sSL https://raw.githubusercontent.com/urbancompasspony/bashrc/main/install.sh | bash
    . .bashrc
    sudo pacman -Syu dialog
    touch /home/$USER/.installed
    init
  } || {
    clear
    echo "Por favor, insira a senha do usuário $USER!"
    echo ""
    curl -sSL https://raw.githubusercontent.com/urbancompasspony/bashrc/main/install.sh | bash
    . .bashrc    
    sudo apt update
    sudo apt install sshpass dialog curl lm-sensors arp-scan traceroute libatasmart-bin udpcast cifs-utils
    touch /home/$USER/.installed
    init
    }
} && {
  init
}

exit 1
