#!/bin/bash

# For Ubuntu 22.04!
export NEEDRESTART_MODE=a
export DEBIAN_FRONTEND=noninteractive

# Máquinas Virtuais
function menu02 {
[ $(which virt-manager 2>/dev/null) ] && {
  menu022 "1p" && vm1=$vms && vm11=$sts
  menu022 "2p" && vm2=$vms && vm12=$sts
  menu022 "3p" && vm3=$vms && vm13=$sts
  menu022 "4p" && vm4=$vms && vm14=$sts
  menu022 "5p" && vm5=$vms && vm15=$sts
  menu022 "6p" && vm6=$vms && vm16=$sts
  menu022 "7p" && vm7=$vms && vm17=$sts
  menu022 "8p" && vm8=$vms && vm18=$sts
  menu022 "9p" && vm9=$vms && vm19=$sts
  menu022 "10p" && vm10=$vms && vm110=$sts
  menuxy=$(dialog --ok-label 'Ajustar' --help-button --help-label 'Ajuda' --backtitle "Bem-Vindo ao Gestor de Máquinas Virtuais!" --title "Gestão de VMs" --menu "Gestão de Máquinas Virtuais"  0 0 0 \
  Status "Geral" \
  "$vm1" "$vm11" \
  "$vm2" "$vm12" \
  "$vm3" "$vm13" \
  "$vm4" "$vm14" \
  "$vm5" "$vm15" \
  "$vm6" "$vm16" \
  "$vm7" "$vm17" \
  "$vm8" "$vm18" \
  "$vm9" "$vm19" \
  "$vm10" "$vm110" \
  "X Voltar" "" 2>&1 > /dev/tty )
  case $? in
    2) dialog --title "Ajuda" --msgbox "$TEXTAO11" 0 0 ; menu02 ;;
  esac
  [ $? -ne 0 ] && exit
  case "$menuxy" in
  Status) menu025 ;;
  "$vm1") chkvm="$vm11"; nmvm="$vm1"; menu021 ;;
  "$vm2") chkvm="$vm12"; nmvm="$vm2"; menu021 ;;
  "$vm3") chkvm="$vm13"; nmvm="$vm3"; menu021 ;;
  "$vm4") chkvm="$vm14"; nmvm="$vm4"; menu021 ;;
  "$vm5") chkvm="$vm15"; nmvm="$vm5"; menu021 ;;
  "$vm6") chkvm="$vm16"; nmvm="$vm6"; menu021 ;;
  "$vm7") chkvm="$vm17"; nmvm="$vm7"; menu021 ;;
  "$vm8") chkvm="$vm18"; nmvm="$vm8"; menu021 ;;
  "$vm9") chkvm="$vm19"; nmvm="$vm9"; menu021 ;;
  "$vm10") chkvm="$vm110"; nmvm="$vm10"; menu021 ;;
  "X Voltar") exit ;;
  esac
} || {
  dialog --cr-wrap --title 'ERRO DETECTADO' --backtitle "$bktitle" --msgbox "O VirtManager não foi encontrado neste sistema ou você não possui as permissões para acessá-lo!" 7 50
  exit
}

}

function menu021 {
[ "$chkvm" = "Executando" ] && {
  dialog --title "$nmvm" --yesno "Deseja reiniciar a VM $nmvm?" 6 40
  [ $? = 0 ] && {
    virsh reboot "$nmvm"
    dialog --title "$nmvm" --msgbox "A VM $nmvm foi reiniciada!" 6 40
  } || {
    dialog --title "$nmvm" --yesno "Deseja desligar a VM $nmvm?" 6 40
    [ $? = 0 ] && {
      virsh shutdown "$nmvm"
      dialog --title "$nmvm" --msgbox "A VM $nmvm foi desligada!" 6 40
    } || {
      dialog --title "$nmvm" --yesno "Deseja desligar FORÇADAMENTE a VM $nmvm?" 6 40
      [ $? = 0 ] && {
        virsh destroy "$nmvm"
        dialog --title "$nmvm" --msgbox "A VM $nmvm foi desligada de forma forçada!" 6 40
      } || {
        echo "a" > /dev/null
        }
    }
  }
} || {
  [ "$chkvm" = "- - -" ] && {
    dialog --title "$nmvm" --msgbox "A VM $nmvm não existe!" 6 40
  } || {
    [ "$chkvm" = "Parado" ] && {
      dialog --title "$nmvm" --yesno "Deseja tentar ligar a VM $nmvm?" 6 40
      [ $? = 0 ] && {
        virsh start "$nmvm"
        dialog --title "$nmvm" --msgbox "Verifique se a VM $nmvm iniciou!" 6 40
      } || {
        echo "a" > /dev/null
        }
    }
  }
}

menu02
}

# Status das VMs
function menu022 {
vms=$(virsh list | grep running | sed -n "$1" | awk '{print $2}')
[ "$vms" = "" ] && {
  vms=$(virsh list --all | grep "shut off" | sed -n "$1" | awk '{print $2}')
  sts=$(echo "Parado")
  [ "$vms" = "" ] && {
    vms=$(echo "- - -")
    sts=$(echo "- - -")
  } || {
    echo " " > /dev/null
    }
} || {
  sts=$(echo "Executando")
  }

}

function menu023 {
dialog --title 'Confirmação' --backtitle 'Confirmação de Início de Todas as VMs!' --yesno "Deseja inicializar todas as VMs?" 0 0
[ $? -ne 0 ] && menu02

[ $? = 0 ] && {
  for i in $(virsh list --all | grep "shut off" | awk '{print $2}')
  do
    virsh start $i
    dialog --title 'Status:' --msgbox "VM $i Iniciada!" 0 0
  done
} || {
  echo "a" > /dev/null
  }

menu02
}

function menu024 {
dialog --title 'Confirmação' --backtitle 'Confirmação de Desligamento de Todas as VMs!' --yesno "Deseja desligar todas as VMs?" 0 0
[ $? -ne 0 ] && menu02

[ $? = 0 ] && {
  for i in $(virsh list | grep running | awk '{print $2}')
  do
    virsh shutdown $i
    dialog --title 'Status:' --msgbox "VM $1 desligada!" 0 0
  done
} || {
  echo "a" > /dev/null
  }

menu02
}

# Status de Máquinas Virtuais
function menu025 {
virtmgr0=$(virsh list --all)
dialog --cr-wrap --help-button --help-label 'Ajuda' --title "Maquinas Virtuais encontradas:" --backtitle "$bktitle" --msgbox "$virtmgr0" 0 0
case $? in
  2) dialog --title 'Ajuda' --msgbox "$TEXTAO12" 0 0 ; menu025 ;;
esac
[ $? -ne 0 ] && exit

menu02
}

menu02
