#!/bin/bash

UNAME_R=$(uname -r)
UNAME_V=$(uname -v | sed 's/ SMP//g' | sed 's/ PREEMPT//g')
UNAME_M=$(uname -m)

echo "";

[ -r /etc/lsb-release ] && . /etc/lsb-release
if [ -z "$DISTRIB_DESCRIPTION" ] && [ -x /usr/bin/lsb_release ]; then
	# Fall back to using the very slow lsb_release utility
	DISTRIB_DESCRIPTION=$(lsb_release -s -d)
fi
HEADER=$(printf "%s (%s)"  "$DISTRIB_DESCRIPTION" "$UNAME_R")
echo $HEADER
#figlet $HEADER
